import localFont from "next/font/local";
import "./globals.css";
import Desktop from "./_components/DesktopView/page";
import Navbar from "./_components/navbar/page";
import Footer from "./_components/footer/page";
import Section4 from "./_components/section4/page";
import Copyright from "./_components/copyright/page";
import useDeviceType from "./_UseDeviceType/page";
import FooterDesktop from "./_components/FooterDesktop/page";
import useWindowWidth from "./_UseDeviceType/page";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 
 
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <link rel="stylesheet" href="/usmobile.css" />
      <link rel="stylesheet" href="/usmobile_home.css" />
      <link rel="stylesheet" href="/US_customcss.css" />
      <link rel="stylesheet" href="/UScustomhome.css" />
      <link href="/Content/css/m.lightpick.css?v=RUS2021" rel="stylesheet" />
      <link href="/bundles/US_mobilehotelcss?v=D5kGZF0-EfG2ZGUlC_qi6vWM1FZ81W3Xv_diatA6Se81" rel="stylesheet" />
      <link rel="stylesheet" href="/Content/css/m.lightpick.css" />
      <script src="/_usemobile.js" >
      </script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        {children}
      
        
      
      </body>
    </html>
  );
}
